export enum QueryParams {
  city = "city",
  country = "country",
  state = "state",
  checkinDate = "checkinDate",
  checkoutDate = "checkoutDate",
  numGuests = "numGuests",
  popularfacilities = "popularfacilities[all]",
  maxPriceRange = "priceRange.max[lte]",
  minPriceRange = "priceRange.min[gte]",
  cabinTypes = "cabinTypes[in]",
  starRating = "starRating[gte]",
  maxBookingLength = "maxBookingLength[gte]",
  ratingAverage = "ratingAverage[gte]",
}
